baseURL               = "https://cunyu1943.github.io/CodeNav"
languageCode          = "zh-CN"
title                 = "程序员工具导航 ｜ 基于村雨遥的好物周刊"
theme                 = "WebStack-Hugo"
preserveTaxonomyNames = true
disablePathToLower    = true
hasCJKLanguage        = true
publishDir            = "public"

[params]
    author        = "cunyu1943"
    description   = "程序员工具导航 ｜ 基于村雨遥的好物周刊"
    upload        = "https://wj.qq.com/s2/13360545/da29/"
    about         = "https://www.yuque.com/cunyu1943"	# 左侧导航栏的"关于我们"页面(./about)
    repository    = "https://github.com/cunyu1943/CodeNav"	
    enablePreLoad = true                                                        # 网站完全打开前预加载动画
    textPreLoad   = "村雨遥的好物周刊"                                              # 预加载的动画文字, 只有当enablePreLoad=true时生效
    expandSidebar = true                                                       # 默认展开左侧边导航栏
    logosPath     = "assets/images/logos"	                # 网站每个导航地址logo存放地址
    defaultLogo   = "assets/images/logos/default.svg"    # logo图片资源不存在或者错误时, 默认显示的logo; 该参数如为空,将会一直加载对应的logo,直至成功
    nightMode     = false							                            # 默认站点为深色(夜间)模式
    yiyan         = true                                        		        # 默认启用一言服务

[params.seo]
    baiduhmid       = 'a65c08a1c6ad31ab8162591e3c4b2fc1'             		# 百度统计 hm.src 的 ID
    baiduSiteVer    = 'codeva-cCAOSG8MBO'                            		# 百度HTML标签验证(baidu-site-verification)    
    tj51laid        = ''                                        		    # 51.LA 网站统计
    tj51lack        = ''
    GoogleAdsClient = 'ca-pub-9356811841483300'

[params.qweather]
    key = "085791e805a24491b43b06cf58ab31e7"

[params.images]
    favicon           = "assets/images/favicon.png"
    searchImageL      = "assets/images/bg-dna.jpg"		  # 搜索部分浅色背景图
    searchImageD      = "assets/images/bg-dna.jpg"		  # 搜索部分深色背景图
    logoExpandLight   = "assets/images/bt8-expand-light.png"
    logoExpandDark    = "assets/images/bt8-expand-dark.png"
    logoCollapseLight = "assets/images/bt.png"
    logoCollapseDark  = "assets/images/bt.png"

[markup.goldmark.renderer]
    unsafe = true

[params.footer]
    copyright = '本站内容源自互联网，如有内容侵犯了你的权益，请联系删除相关内容，联系邮箱：<a href="mailto:747731461@qq.com?subject=程序员资源导航意见反馈" target="_blank">747731461@qq.com</a> <br/>&copy; 2023 - {year} By [村雨遥](https://github.com/cunyu1943/)'