name: Hugo Actions  # 名字自取

on:
  push:
    branches:
      - main  # 这里的意思是当 main 分支发生 push 的时候，运行下面的 jobs

jobs:
  deploy: 
    runs-on: ubuntu-20.04	        # 在什么环境运行任务
    steps:
      - uses: actions/checkout@v3       # 引用actions/checkout这个action，与所在的github仓库同名
        with:
         submodules: true               # Fetch Hugo themes (true OR recursive) 获取submodule主题
         fetch-depth: 0                 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo	        # 步骤名自取
        uses: peaceiris/actions-hugo@v2	# hugo官方提供的action，用于在任务环境中获取hugo
        with:
          hugo-version: 'latest'	# 获取指定版本的hugo

      - name: Build 
        #run: hugo --minify	# 使用 hugo 构建静态网页
        run: hugo         	# 使用 hugo 构建静态网页

      - name: 部署文档
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # 这是文档部署到的分支名称
          branch: gh-pages
          folder: ./public
          token: ${{ secrets.TOKEN }}
          repository-name: cunyu1943/CodeNav